<a href="https://colab.research.google.com/github/MadhavKrishna09/Pytorch/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction of tensors

### Creating tensors



In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#vector
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [7]:
#MATRIX

MATRIX  = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([3, 3])

In [10]:
MATRIX[0]

tensor([1, 2, 3])

In [11]:
TENSOR = torch.tensor([[[[1,2,3],[1,2,3],[1,2,3]]]])
TENSOR

tensor([[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]])

In [12]:
TENSOR.ndim

4

In [13]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

###Random Tensors

`Start with random numbers-> look at data-> update random numbers -> look at data -> update random numbers`


In [14]:
# create a random tensors of size(3,4)

random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.0787, 0.8502, 0.0732, 0.0830],
        [0.1117, 0.1740, 0.4834, 0.1734],
        [0.3362, 0.0598, 0.6625, 0.0750]])

In [15]:
# for image
random_image_size_tensors = torch.rand(size = (3,224,224)) #height,width,colour channel
random_image_size_tensors.shape, random_image_size_tensors.ndim

(torch.Size([3, 224, 224]), 3)

In [16]:
## tensors of zeroes
zeroes = torch.zeros(3,4)

In [17]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like

In [19]:
# Use torch.range()
one_to_ten = torch.arange(start = 0,end = 1000, step = 100)

In [20]:
# Tensors like
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors data type

In [21]:
# FLoat 32 tensor

float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype=None,# datatype of tensor(float32, float16)
                                device = None)

float_32_tensor

tensor([3., 4., 5.])

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [24]:
!git version


git version 2.34.1


In [25]:
!git config --global user.email “krishnamadhav923@gmail.com”

!git config --global user.name “MadhavKrishna09”

In [26]:
token = "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"
username = "MadhavKrishna09"
repo = "Pytorch"

In [27]:
!git clone https://{token}@github.com/{username}/{repo}

Cloning into 'Pytorch'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.


In [28]:
!git status

fatal: not a git repository (or any of the parent directories): .git


In [29]:
!git add --all

fatal: not a git repository (or any of the parent directories): .git


In [30]:
%cd {repo}

/content/Pytorch


In [31]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


### Matrix multiplication

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [33]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [34]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.55 ms, sys: 0 ns, total: 1.55 ms
Wall time: 4.68 ms


tensor(14)

In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 396 µs, sys: 70 µs, total: 466 µs
Wall time: 391 µs


tensor(14)

### Finding the min, max, mean, sum, etc (aggregation)

In [37]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [39]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [40]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0
