<a href="https://colab.research.google.com/github/MadhavKrishna09/Pytorch/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction of tensors

### Creating tensors



In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [11]:
#vector
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([3])

In [14]:
#MATRIX

MATRIX  = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([3, 3])

In [17]:
MATRIX[0]

tensor([1, 2, 3])

In [18]:
TENSOR = torch.tensor([[[[1,2,3],[1,2,3],[1,2,3]]]])
TENSOR

tensor([[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]])

In [19]:
TENSOR.ndim

4

In [20]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

###Random Tensors

`Start with random numbers-> look at data-> update random numbers -> look at data -> update random numbers`


In [3]:
# create a random tensors of size(3,4)

random_tensors = torch.rand(3,4)
random_tensors

tensor([[0.3940, 0.3815, 0.9792, 0.0613],
        [0.4875, 0.4550, 0.1133, 0.4781],
        [0.1690, 0.3694, 0.6146, 0.1818]])

In [5]:
# for image
random_image_size_tensors = torch.rand(size = (3,224,224)) #height,width,colour channel
random_image_size_tensors.shape, random_image_size_tensors.ndim

(torch.Size([224, 224, 3]), 3)

In [7]:
## tensors of zeroes
zeroes = torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
ones.dtype


torch.float32

### Creating a range of tensors and tensors-like

In [18]:
# Use torch.range()
one_to_ten = torch.arange(start = 0,end = 1000, step = 100)

In [20]:
# Tensors like
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors data type

In [30]:
# FLoat 32 tensor

float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype=None,# datatype of tensor(float32, float16)
                                device = None)

float_32_tensor

tensor([3., 4., 5.])

In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])